// This file is automatically generated. Do not modify it manually.

// Your web app's Firebase configuration
// For more information on how to use this object, see the following page:
// https://firebase.google.com/docs/web/setup#available-libraries

export const firebaseConfig = {
  apiKey: "placeholder-api-key",
  authDomain: "placeholder-auth-domain",
  projectId: "placeholder-project-id",
  storageBucket: "placeholder-storage-bucket",
  messagingSenderId: "placeholder-messaging-sender-id",
  appId: "placeholder-app-id",
  measurementId: "placeholder-measurement-id"
};
